site_name: Τεκμηρίωση Γεωπληροφοριακού Συστήματος GeoDataHub
site_description: Τεκμηρίωση & οδηγός χρήσης για το GeoDataHub, το
        γεωπληροφοριακό σύστημα του Ελληνικού Κέντρου Διαστήματος.
site_author: Hellenic Space Center & Geospatial Enabling Technologies
site_url: https://docs.geodatahub.hsc.gr
repo_url: https://github.com/HellenicSpaceCenter/geodatahub-doc
repo_name: geodatahub-doc
edit_uri: edit/main/docs
extra_css:
        - assets/custom.css
theme:
        name: material
        logo: assets/logo.png
        favicon: assets/favicon.ico
        icon:
                repo: fontawesome/brands/github
        palette:
                # Light mode
                - media: "(prefers-color-scheme: light)"
                  scheme: default
                  toggle:
                          icon: material/brightness-7
                          name: Switch to dark mode
                # Dark mode
                - media: "(prefers-color-scheme: dark)"
                  scheme: slate
                  toggle:
                          icon: material/brightness-4
                          name: Switch to light mode
        features:
                - navigation.tabs
                - navigation.sections
                - navigation.expand
                - navigation.top
                - navigation.tracking
                - search.suggest
                - search.highlight
                - content.code.copy
                - content.code.annotate
                - content.action.view
                - content.action.edit
                - toc.follow

plugins:
        - search
        - tags
        - macros
        - git-revision-date-localized:
                  enable_creation_date: true
        - git-committers:
                  repository: HellenicSpaceCenter/geodatahub-erm
                  branch: main
                  token: ${GITHUB_TOKEN} # Use an environment variable for the token

markdown_extensions:
        - admonition
        - pymdownx.details
        - pymdownx.blocks.caption
        - pymdownx.superfences:
                  custom_fences:
                          - name: mermaid
                            class: mermaid
                            format: !!python/name:pymdownx.superfences.fence_code_format ""
        - pymdownx.tabbed:
                  alternate_style: true
        - pymdownx.highlight:
                  anchor_linenums: true
        - pymdownx.inlinehilite
        - pymdownx.snippets
        - attr_list
        - md_in_html
        - tables
        - toc:
                  permalink: true
nav:
        - Αρχική: index.md
        # - Getting Started:
        #           - Overview: getting-started/overview.md
        #           - Quick Start: getting-started/quickstart.md
        #           - Installation & Setup: getting-started/installation.md
        - Οδηγός Διαχειριστή:
                  - Επισκόπηση: admin-guide/overview.md
                  - Μηχανή Ροής Εργασίας:
                            - Ροές Εργασίας: admin-guide/workflow-engine/workflows.md
                            - Κόμβοι: admin-guide/workflow-engine/nodes.md
                            - Φόρμες: admin-guide/workflow-engine/forms.md
        # - Οδηγός Χρήστη:
        #           - Επισκόπηση: user-guide/overview.md
        #           - Πίνακας Ελέγχου: user-guide/dashboard.md
        #           - Δημιουργία Παραγγελιών: user-guide/creating-orders.md
        #           - Διαχείριση Παραγγελιών: user-guide/order-management.md
        #           - Ροές Εργασίας: user-guide/workflows.md
        #           - Συνεργασία μέσω Συνομιλίας: user-guide/chat.md
        #           - Διαχείριση Αρχείων: user-guide/file-management.md
        #           - Παραδοτέα: user-guide/deliverables.md
        #           - Αναφορές & Αναλύσεις: user-guide/analytics.md
        #           - Συχνές Ερωτήσεις: user-guide/faq.md

        - DevOps:
                  - Επισκόπηση: devops/overview.md
                  #   - Ανάπτυξη: devops/deployment.md
                  #   - CI/CD: devops/ci-cd.md
                  #   - Παρακολούθηση & Καταγραφή: devops/monitoring.md
                  #   - Κλιμάκωση & Απόδοση: devops/scaling.md
