site_name: GeodataHub User Manual
site_description: User manual for the GeodataHub platform, providing
        comprehensive documentation for administrators and users.
site_author: Hellenic Space Center & Geospatial Enabling Technologies
site_url: https://docs.geodatahub.hsc.gr
repo_url: https://github.com/HellenicSpaceCenter/geodatahub-doc
repo_name: geodatahub-doc
edit_uri: edit/main/docs
extra_css:
        - assets/custom.css
theme:
        name: material
        logo: assets/logo.png
        favicon: assets/favicon.ico
        icon:
                repo: fontawesome/brands/github
        palette:
                # Light mode
                - media: "(prefers-color-scheme: light)"
                  scheme: default
                  toggle:
                          icon: material/brightness-7
                          name: Switch to dark mode
                # Dark mode
                - media: "(prefers-color-scheme: dark)"
                  scheme: slate
                  toggle:
                          icon: material/brightness-4
                          name: Switch to light mode
        features:
                - navigation.tabs
                - navigation.sections
                - navigation.expand
                - navigation.top
                - navigation.tracking
                - search.suggest
                - search.highlight
                - content.code.copy
                - content.code.annotate
                - content.action.view
                - content.action.edit
                - toc.follow

extra:
        social_image: assets/embed-banner.png
        social_image_alt: GeoDataHub Documentation
        twitter_card: summary_large_image

plugins:
        - search
        - tags
        - macros
        - git-revision-date-localized:
                  enable_creation_date: true
        - git-committers:
                  repository: HellenicSpaceCenter/geodatahub-erm
                  branch: main
                  token: ${GITHUB_TOKEN} # Use an environment variable for the token

markdown_extensions:
        - admonition
        - pymdownx.details
        - pymdownx.blocks.caption
        - pymdownx.superfences:
                  custom_fences:
                          - name: mermaid
                            class: mermaid
                            format: !!python/name:pymdownx.superfences.fence_code_format ""
        - pymdownx.tabbed:
                  alternate_style: true
        - pymdownx.highlight:
                  anchor_linenums: true
        - pymdownx.inlinehilite
        - pymdownx.snippets
        - attr_list
        - md_in_html
        - tables
        - toc:
                  permalink: true
nav:
        - Home: index.md
        - Administrator Guide:
                  - Overview: admin-guide/overview.md
                  - Platform Settings: admin-guide/platform-settings.md
                  - Workflow Engine:
                            - Workflows: admin-guide/workflow-engine/workflows.md
                            - Nodes: admin-guide/workflow-engine/nodes.md
                    #             - Forms: admin-guide/workflow-engine/forms.md
                  - Users:
                            - Overview: admin-guide/users/index.md
                            - User Management: admin-guide/users/management.md
                  - Organizations & Workspaces:
                                - Overview: admin-guide/orgs/index.md
        - User Guide:
                  - Overview: user-guide/overview.md
        #           - Dashboard: user-guide/dashboard.md
        #           - Creating Orders: user-guide/creating-orders.md
        #           - Order Management: user-guide/order-management.md
        #           - Workflows: user-guide/workflows.md
        #           - Chat Collaboration: user-guide/chat.md
        #           - File Management: user-guide/file-management.md
        #           - Deliverables: user-guide/deliverables.md
        #           - Reports & Analytics: user-guide/analytics.md
        #           - FAQ: user-guide/faq.md

